- id: arXiv:2305.02480
- id: arXiv:2303.15375
- id: doi:10.1109/ISOCC.2017.8368829
- id: doi:10.1016/j.sysarc.2023.103025
- id: doi:10.1109/ISCA59077.2024.00051
- id: doi:10.1109/ISCA59077.2024.00066


# Demystifying a CXL Type-2 device: A heterogeneous cooperative computing perspective
- title: Demystifying a CXL Type-2 device: A heterogeneous cooperative computing perspective
  authors:
    - Houxiang Ji
    - Srikar Vanavasam
    - Yang Zhou
    - Qirong Xia
    - Jinghan Huang
    - Yifan Yuan
    - Ren Wang
    - Pekon Gupta
    - Bhushan Chitlur
    - Ipoom Jeong
    - Nam Sung Kim
  publisher: IEEE/ACM International Symposium on Microarchitecture (MICRO, accepted)
  date: 2024-11-02
  
# HAL: Hardware-assisted Load Balancing for Energy-efficient SNIC-Host Cooperative Computing
- id: doi:10.1109/ISCA59077.2024.00051
  publisher: ACM/IEEE International Symposium on Computer Architecture (ISCA)
  tags:
    - Network
    - Near-data processing
    - SmartNIC
    - Load balancing
    - CXL
  image: /images/spr_die_xcc.png
  
# Intel Accelerators Ecosystem: An SoC-Oriented Perspective: Industry Product
- id: doi:10.1109/ISCA59077.2024.00066
  publisher: ACM/IEEE International Symposium on Computer Architecture (ISCA)
  tags:
    - CPU
    - On-chip accelerator
    - Server SoC
  image: /images/spr_die_xcc.png

# Triple-A: Early Operand Collector Allocation for Maximizing GPU Register Bank Utilization
- id: 10.1109/LES.2023.3307622
  publisher: IEEE Embedded Systems Letters
  tags:
    - GPU
    - Register file
    - Operand collection
  image: /images/spr_die_xcc.png
  
- id: doi:10.1145/3620666.3651325
  publisher: ACM Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS)

- id: doi:10.1145/3620665.3640401
  publisher: ACM Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS)

- id: doi:10.1145/3627703.3629588
  publisher: ACM SIGOPS European Conference on Computer Systems (EuroSys)

- id: doi:10.1016/j.sysarc.2023.103025
  publisher: Journal of Systems Architecture

- id: doi:10.1145/3613424.3614256
  publisher: IEEE/ACM International Symposium on Microarchitecture (MICRO)

- id: doi:10.1109/pact58117.2023.00033
  publisher: ACM International Conference on Parallel Architectures And Compilation Techniques (PACT)
  
- id: doi:10.1109/micro56248.2022.00023
  publisher: IEEE/ACM International Symposium on Microarchitecture (MICRO)
  
- id: doi:10.1109/hpca47549.2020.00039
  publisher: IEEE International Symposium on High Performance Computer Architecture (HPCA)
  
- id: doi:10.1109/ISOCC.2017.8368829
  title: Parallel In-Order Execution Architecture for Low-Power Processor


# manually provide all citation details
- title: A Multi-DNN Acceleration Architecture for Balanced QoS and Throughput
  authors:
    - Ipoom Jeong
    - Sungji Choi
    - Minjae Kim
    - Enhyeok Jang
    - Seokjin Go
    - Won Woo Ro
  publisher: International Conference on Electronics, Information, and Communication (ICEIC)
  date: 2024-01-28

- title: Constructing Resilient Region in Dynamic Optimization Systems via Dynamic Adjustment of Bias Thresholds
  authors:
    - Ipoom Jeong
    - Won Woo Ro
  publisher: IEEE International Conference On Consumer Electronics Asia (ICCE-ASIA)
  date: 2018-06-01

- title: Dynamic Warp Scheduler Selection Policy Using Linear Regression for GPUs
  authors:
    - Hyunjun Shin
    - Kyungmin Lee
    - Ipoom Jeong
    - Jong Hyun Park
    - Won Woo Ro
  publisher: International Conference on Electronics, Information, and Communication (ICEIC)
  date: 2017-01-01

- title: Heterogeneous Core Microarchitecture with Functional Unit Gating for High Energy Efficiency
  authors:
    - Yoonsoo Kim
    - Ipoom Jeong
    - Won Woo Ro
  publisher: Annual Summer Conference of IEIE
  date: 2016-06-01

- title: Analyzing Development Trends and Performance/Power Characteristics of Multi-Core Processors
  authors:
    - Ipoom Jeong
    - Won Woo Ro
  publisher: Annual Summer Conference of IEIE
  date: 2016-06-01

- title: Exploiting Back-End Fusion in Multi-Core Processors
  authors:
    - Jonghyun Park
    - Ipoom Jeong
    - Won Woo Ro
  publisher: Annual Fall Conference of KIPS
  date: 2014-11-01
