- id: arXiv:2305.02480
- id: arXiv:2303.15375
- id: doi:10.1016/j.sysarc.2023.103025
- id: doi:10.1109/ISCA59077.2024.00051
- id: doi:10.1109/ISCA59077.2024.00066
- id: doi:10.1109/MICRO61859.2024.00110

# Demystifying a CXL Type-2 Device: A Heterogeneous Cooperative Computing Perspective
- id: doi:10.1109/MICRO61859.2024.00110
  publisher: IEEE/ACM International Symposium on Microarchitecture (MICRO), BK21+
  tags:
    - System
    - Memory
    - Accelerator
    - Interconnect
  image: /images/publications/system.jpg
  
# HAL: Hardware-assisted Load Balancing for Energy-efficient SNIC-Host Cooperative Computing
- id: doi:10.1109/ISCA59077.2024.00051
  publisher: ACM/IEEE International Symposium on Computer Architecture (ISCA)
  tags:
    - System
    - Network
    - Interconnect
    - Architecture
    - Accelerator
  image: /images/publications/system.jpg
  
# Intel Accelerators Ecosystem: An SoC-Oriented Perspective: Industry Product
- id: doi:10.1109/ISCA59077.2024.00066
  publisher: ACM/IEEE International Symposium on Computer Architecture (ISCA)
  tags:
    - System
    - CPU
    - Architecture
    - Accelerator
  image: /images/publications/system.jpg

# Triple-A: Early Operand Collector Allocation for Maximizing GPU Register Bank Utilization
- id: doi:10.1109/LES.2023.3307622
  publisher: IEEE Embedded Systems Letters
  tags:
    - GPU
    - Microarchitecture
  image: /images/publications/gpu.png

# TAROT: A CXL SmartNIC-Based Defense Against Multi-bit Errors by Row-Hammer Attacks
- id: doi:10.1145/3620666.3651325
  publisher: ACM Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS)
  tags:
    - System
    - Memory
    - Interconnect
    - Architecture
    - Security
  image: /images/publications/system.jpg

# A Quantitative Analysis and Guidelines of Data Streaming Accelerator in Modern Intel Xeon Scalable Processors
- id: doi:10.1145/3620665.3640401
  publisher: ACM Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS)
  tags:
    - CPU
    - Architecture
    - Accelerator
  image: /images/publications/acc.png
  
# ScaleCache: A Scalable Page Cache for Multiple Solid-State Drives
- id: doi:10.1145/3627703.3629588
  publisher: ACM SIGOPS European Conference on Computer Systems (EuroSys)
  tags:
    - System
    - Storage
    - OS    
  image: /images/publications/ssd.jpg

# A Quantitative Analysis and Guidelines of Data Streaming Accelerator in Modern Intel Xeon Scalable Processors
- id: arXiv:2305.02480
  tags:
    - CPU
    - Architecture
    - Accelerator
  image: /images/publications/acc.png

# A convertible neural processor supporting adaptive quantization for real-time neural networks
- id: doi:10.1016/j.sysarc.2023.103025
  title: A Convertible Neural Processor Supporting Adaptive Quantization for Real-Time Neural Networks
  publisher: Journal of Systems Architecture
  tags:
    - NPU
    - Architecture
    - Accelerator
  image: /images/publications/acc.png

# Demystifying CXL Memory with Genuine CXL-Ready Systems and Devices
- id: doi:10.1145/3613424.3614256
  publisher: IEEE/ACM International Symposium on Microarchitecture (MICRO)
  tags:
    - System
    - Memory
    - Interconnect
  image: /images/publications/memory.jpg

# INTERPRET: Inter-Warp Register Reuse for GPU Tensor Core
- id: doi:10.1109/pact58117.2023.00033
  publisher: ACM International Conference on Parallel Architectures And Compilation Techniques (PACT)
  tags:
    - GPU
    - Microarchitecture
  image: /images/publications/gpu.png

# Demystifying CXL Memory with Genuine CXL-Ready Systems and Devices
- id: arXiv:2303.15375
  tags:
    - System
    - Memory
    - Interconnect
  image: /images/publications/memory.jpg
  
# LADIO: Leakage-Aware Direct I/O for I/O-Intensive Workloads
- id: doi:10.1109/LCA.2023.3290427
  tags:
    - System
    - Storage
    - Network
    - CPU
  image: /images/publications/system.jpg
  
# CASH-RF: A Compiler-Assisted Hierarchical Register File in GPUs
- id: doi:10.1109/LES.2022.3163749
  tags:
    - GPU
    - Microarchitecture
  image: /images/publications/gpu.png
  
# Reconstructing Out-of-Order Issue Queue
- id: doi:10.1109/micro56248.2022.00023
  publisher: IEEE/ACM International Symposium on Microarchitecture (MICRO)
  tags:
    - CPU
    - Microarchitecture
  image: /images/publications/cpu.png

# TEA-RC: Thread Context-Aware Register Cache for GPUs
- id: doi:10.1109/ACCESS.2022.3196149
  tags:
    - GPU
    - Microarchitecture
  image: /images/publications/gpu.png

# CASINO Core Microarchitecture: Generating Out-of-Order Schedules Using Cascaded In-Order Scheduling Windows
- id: doi:10.1109/hpca47549.2020.00039
  publisher: IEEE International Symposium on High Performance Computer Architecture (HPCA)
  tags:
    - CPU
    - Microarchitecture
  image: /images/publications/cpu.png

# OverCome: Coarse-Grained Instruction Commit with Handover Register Renaming
- id: doi:10.1109/TC.2019.2936557
  tags:
    - CPU
    - Microarchitecture
  image: /images/publications/cpu.png
  
# Parallel In-Order Execution Architecture for Low-Power Processor
- id: doi:10.1109/isocc.2017.8368829
  title: Parallel In-Order Execution Architecture for Low-Power Processor
  publisher: International SoC Design Conference (ISOCC)
  tags:
    - CPU
    - Microarchitecture
  image: /images/publications/cpu.png
  

# manually provide all citation details
- title: A Multi-DNN Acceleration Architecture for Balanced QoS and Throughput
  authors:
    - Ipoom Jeong
    - Sungji Choi
    - Minjae Kim
    - Enhyeok Jang
    - Seokjin Go
    - Won Woo Ro
  publisher: International Conference on Electronics, Information, and Communication (ICEIC)
  date: 2024-01-28

- title: Constructing Resilient Region in Dynamic Optimization Systems via Dynamic Adjustment of Bias Thresholds
  authors:
    - Ipoom Jeong
    - Won Woo Ro
  publisher: IEEE International Conference On Consumer Electronics Asia (ICCE-ASIA)
  date: 2018-06-01

- title: Dynamic Warp Scheduler Selection Policy Using Linear Regression for GPUs
  authors:
    - Hyunjun Shin
    - Kyungmin Lee
    - Ipoom Jeong
    - Jong Hyun Park
    - Won Woo Ro
  publisher: International Conference on Electronics, Information, and Communication (ICEIC)
  date: 2017-01-01

- title: Heterogeneous Core Microarchitecture with Functional Unit Gating for High Energy Efficiency
  authors:
    - Yoonsoo Kim
    - Ipoom Jeong
    - Won Woo Ro
  publisher: Annual Summer Conference of IEIE
  date: 2016-06-01

- title: Analyzing Development Trends and Performance/Power Characteristics of Multi-Core Processors
  authors:
    - Ipoom Jeong
    - Won Woo Ro
  publisher: Annual Summer Conference of IEIE
  date: 2016-06-01

- title: Exploiting Back-End Fusion in Multi-Core Processors
  authors:
    - Jonghyun Park
    - Ipoom Jeong
    - Won Woo Ro
  publisher: Annual Fall Conference of KIPS
  date: 2014-11-01
